### ISSUE TITLE
Pripravit katalog poziadaviek

### ISSUE THREAD

**Issue by MartinHeinz** [TIS2016/Sportovy-klub#8]
Pripravit katalog poziadaviek podla poziadaviek zadavatela a podla dohodnutych veci zo zapisnic do 11.10

**Comment by michalpuskel** [comment]
nahram do gitu ti verziu co mi dal Tomas do extra branchu aby sme stihli deadline a ked vyexportujes pls tu upravenu spec.tex tak sa to moze nahrat potom tam...

**Comment by michalpuskel** [comment]
resp radsej dam tam uz upravenu spec.tex teda to pdf este treba vyexportovat

**Comment by michalpuskel** [comment]
toto uz mame asi hotove staci mergnut speci do mastra apotom sa moze zavret
